# Generated by Django 4.2.1 on 2023-05-26 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teleconsults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField()),
                ("duration", models.CharField(max_length=255)),
                ("communication_medium", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teleconsults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teleconsults",
                "ordering": ("posted_at",),
            },
        ),
        migrations.CreateModel(
            name="Locum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("facility", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("shift_starts", models.DateTimeField()),
                ("shift_ends", models.DateTimeField()),
                ("rate_per_shift", models.FloatField()),
                ("contact", models.CharField(max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="locums", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Locum slots",
                "ordering": ("posted_at",),
            },
        ),
    ]
