# Generated by Django 4.1.9 on 2023-05-19 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slots", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teleconsults",
        ),
    ]
