# Generated by Django 4.1.9 on 2023-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="Kafui", max_length=30, verbose_name="First Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Doe", max_length=30, verbose_name="Last Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="mdc_registration_no",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="MDC Registration No."),
        ),
        migrations.AddField(
            model_name="user",
            name="register_as",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("pa", "Physician Assistant"),
                    ("patient", "Patient"),
                    ("employer", "Employer"),
                ],
                default="Doctor",
                max_length=30,
                verbose_name="Register as",
            ),
            preserve_default=False,
        ),
    ]
