# Generated by Django 4.1.9 on 2023-06-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_name_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="category",
            field=models.CharField(max_length=30, null=True, verbose_name="Category"),
        ),
        migrations.AddField(
            model_name="user",
            name="contact",
            field=models.CharField(max_length=30, null=True, verbose_name="Contact"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_provisional_reg",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="register_type",
            field=models.CharField(max_length=30, null=True, verbose_name="Register Type"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.BooleanField(default=False, verbose_name="Verification Status"),
        ),
    ]
